import cv2 as cv

img = input("Enter the image path: ")
img = cv.imread(img)

if img is not None:
    print("Chose what operation you want to perform: \n1. Draw circle \n2.draw line \n3. Draw rectangle \n4 add textt ")
    if(input()== '1'):
        print("Enter the center of circle for x: ")
        pt1 = int(input())
        print("Enter the center of circle for y: ")
        pt2 = int(input())
        print("Enter the radius of circle: ")
        radius = int(input())
        print("Enter the color of circle in BGR format (e.g. 255,0,0): ")
        color = input()
        print("Enter the thickness of circle: ")
        thickness = int(input())
        cv.circle(img, (pt1, pt2), radius, tuple(map(int, color.split(','))), thickness)
        cv.imshow('circle', img)
        cv.waitKey(0)  
        cv.destroyAllWindows()

       
    elif(input() == '2'):
        print("Enter the point for line start at X:")
        pt3 = int(input())
        print("Enter the point for line start at Y: ")
        pt4 = int(input())
        print("Enter the colour of line in BGR format: ")
        color = input()
        print("Enter the thickness of line:")
        thck = int(input())
        img = cv.line(img,(pt3,pt4),tuple(map(int, color.split(','))), thck)
        cv.imshow("line", img)
        cv.waitKey(0)
        cv.destroyAllWindows()
    elif(input()=="3"):
        print("Enter the points for rectangle start at X: ")
        pt5 = int(input())
        print("Enter the points for rectangle End at X: ")
        pt6 = int(input())
        print("enter the points for rectangle start at Y:")
        pt7 = int(input())
        print("Enter the colour of line in BGR format: ")
        pt8 = int(input())
        color = input()
        print("Enter the thickness of rectangle: ")
        thck = int(input())
        cv.rectangle(img, (pt5, pt7), (pt6, pt8), tuple(map(int, color.split(','))), thck)
        cv.imshow('rectangle', img)
        cv.waitKey(0)
        cv.destroyAllWindows() 
    elif(input() == '4'):
        print("Enter the text you want to add: ")
        text = input()
        print("Enter the position for text start at X: ")
        pt9 = int(input())
        print("Enter the position for text start at Y: ")
        pt10 = int(input())
        print("Enter the font scale: ")
        font_scale = float(input())
        print("Enter the color of text in BGR format (e.g. 255,0,0): ")
        color = input()
        print("Enter the thickness of text: ")
        thickness = int(input())
        cv.putText(img, text, (pt9, pt10), cv.FONT_HERSHEY_SIMPLEX, font_scale, tuple(map(int, color.split(','))), thickness)
        cv.imshow('text', img)
        cv.waitKey(0)
        cv.destroyAllWindows()
else:
    print("could not load img")